name: Merge-Tests
on:
  push:
    branches: [ master ]

env:
  KEY_HEADER: "X-API-KEY: dxvsGbW25QZHnFBBNN496DxVF19QUtTatyqWPNpa"
  PAYLOAD: "{ \"gitHub\": { \"owner\": \"mohsin_encora\", \"repo\": \"https://github.com/mohsin-encora/Reflect\", \"sha\": \"${{ github.event.pull_request.head.sha }}\" } }"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Reflect tests
        run: curl
             -X POST
             -H "$KEY_HEADER"
             -d "$PAYLOAD"
             -s
             https://api.reflect.run/v1/suites/demosuite/executions
